# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-11-27 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=200, null=True)),
                ('frequency', models.IntegerField(choices=[(10400, '4 hours'), (31200, '12 hours'), (62400, '24 hours'), (172800, '2 days'), (345600, '4 days'), (604800, '1 week')])),
                ('delivery_time', models.DateTimeField()),
                ('query', models.CharField(max_length=500)),
                ('feed_type', models.BooleanField(default=False)),
                ('copies', models.NullBooleanField()),
                ('latest_url', models.CharField(max_length=200, null=True)),
                ('feeds', models.CharField(max_length=600, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('string', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
