# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-04 15:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0003_auto_20161204_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curate_customer',
            name='expires',
            field=models.DateField(null=True),
        ),
    ]
