# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-04 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0004_auto_20161204_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curate_customer',
            name='expires',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='curate_query',
            name='clustering',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='curate_query',
            name='processed_words',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
