# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-04 15:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0005_auto_20161204_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curate_customer',
            name='expires',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='curate_customer',
            name='key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
