# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0011_auto_20161205_1425'),
        ('curate', '0006_auto_20161204_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='curate_customer',
            name='sources',
            field=models.ManyToManyField(to='scope.Source'),
        ),
    ]
