# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-05 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0007_curate_customer_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curate_customer',
            name='sources',
        ),
    ]
