# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-11 17:18


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0015_auto_20161211_1112'),
        ('curate', '0009_article_curate_query_is_mistake'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_curate_query',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scope.Agent'),
        ),
    ]
