# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-20 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0012_auto_20161220_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_curate_query',
            name='selection_options',
            field=models.ManyToManyField(blank=True, to='curate.Curate_Customer_Selection'),
        ),
    ]
