# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-22 08:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0013_auto_20161220_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='curate_customer_selection',
            name='type',
            field=models.CharField(choices=[(b'sel', b'selection'), (b'mis', b'mistake'), (b'oth', b'other')], default=b'sel', max_length=3),
        ),
    ]
