# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-22 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0014_curate_customer_selection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='curate_query',
            name='selection_made',
            field=models.BooleanField(default=False),
        ),
    ]
