# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-24 19:49


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0021_article_pubdate'),
        ('curate', '0015_curate_query_selection_made'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curate_Rejection_Reasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curate.Curate_Customer_Selection')),
            ],
        ),
        migrations.AddField(
            model_name='curate_customer',
            name='bad_source',
            field=models.ManyToManyField(blank=True, to='scope.Source'),
        ),
    ]
