# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-24 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0016_auto_20170124_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curate_rejection_reasons',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reason', to='curate.Curate_Customer_Selection'),
        ),
    ]
