# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-25 19:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0017_auto_20170124_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='curate_customer',
            name='too_frequent',
            field=models.ManyToManyField(blank=True, to='curate.Article_Curate_Query'),
        ),
        migrations.AddField(
            model_name='curate_rejection_reasons',
            name='type',
            field=models.CharField(choices=[(b'sou', b'bad source'), (b'con', b'bad content'), (b'frq', b'too frequent'), (b'oth', b'other')], default=b'con', max_length=3),
        ),
    ]
