# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-26 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0018_auto_20170125_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curate_customer_selection',
            old_name='type',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='curate_rejection_reasons',
            old_name='type',
            new_name='kind',
        ),
    ]
