# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-30 13:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0019_auto_20170126_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curate_customer',
            name='too_frequent',
        ),
        migrations.AddField(
            model_name='curate_rejection_reasons',
            name='current_members',
            field=models.ManyToManyField(blank=True, null=True, to='curate.Article_Curate_Query'),
        ),
    ]
