# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-02-11 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0020_auto_20170130_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_curate_query',
            name='bad_article',
            field=models.BooleanField(default=False),
        ),
    ]
