# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-05-22 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0022_auto_20170301_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curate_Query_Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('keywords', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=300)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curate.Article_Curate_Query')),
                ('cluster_articles', models.ManyToManyField(blank=True, related_name='cluster_articles', to='curate.Article_Curate_Query')),
            ],
        ),
    ]
