# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-05-22 20:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0023_curate_query_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curate_rejection_reasons',
            name='current_members',
            field=models.ManyToManyField(blank=True, to='curate.Article_Curate_Query'),
        ),
    ]
