# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0024_auto_20170522_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curate_customer_selection',
            name='color',
            field=models.CharField(default='#fff', max_length=100),
        ),
        migrations.AlterField(
            model_name='curate_customer_selection',
            name='kind',
            field=models.CharField(choices=[('sel', 'selection'), ('mis', 'mistake'), ('oth', 'other')], default='sel', max_length=3),
        ),
        migrations.AlterField(
            model_name='curate_query_cluster',
            name='summary',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='curate_rejection_reasons',
            name='kind',
            field=models.CharField(choices=[('sou', 'bad source'), ('con', 'bad content'), ('frq', 'too frequent'), ('oth', 'other')], default='con', max_length=3),
        ),
    ]
