# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0025_auto_20170601_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curate_query_cluster',
            name='keywords',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='curate_query_cluster',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
