# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0026_auto_20170608_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curate_Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('curate_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curate.Curate_Customer')),
            ],
        ),
        migrations.AlterField(
            model_name='curate_query_cluster',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center', to='curate.Article_Curate_Query'),
        ),
    ]
