# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0027_auto_20170610_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='curate_recipient',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
