# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curate', '0028_curate_recipient_is_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curate_customer',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='curate_customer',
            name='key',
        ),
    ]
