# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0027_auto_20170722_1529'),
        ('curate', '0029_auto_20170722_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Curate_Retrieval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scope.Article')),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scope.RSSFeed')),
                ('newsletter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scope.Newsletter')),
            ],
        ),
        migrations.CreateModel(
            name='Curate_Retrieval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article_curate_query',
            name='agent',
        ),
        migrations.AddField(
            model_name='article_curate_query',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scope.RSSFeed'),
        ),
        migrations.AddField(
            model_name='curate_customer',
            name='feeds',
            field=models.ManyToManyField(blank=True, to='scope.RSSFeed'),
        ),
        migrations.AddField(
            model_name='curate_customer',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(1)),
        ),
        migrations.AddField(
            model_name='curate_customer',
            name='newsletters',
            field=models.ManyToManyField(blank=True, to='scope.Newsletter'),
        ),
        migrations.AddField(
            model_name='article_curate_retrieval',
            name='retrieval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curate.Curate_Retrieval'),
        ),
    ]
