# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scope', '0025_rssfeed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Reader_Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('bad_article', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scope.Article')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scope.RSSFeed')),
            ],
        ),
        migrations.CreateModel(
            name='Reader_Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateField(auto_now_add=True)),
                ('processed_words', models.CharField(blank=True, max_length=200)),
                ('articles_before_filtering', models.IntegerField(blank=True, null=True)),
                ('clustering', models.CharField(blank=True, max_length=200)),
                ('no_clusters', models.IntegerField(blank=True, null=True)),
                ('selection_made', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reader_Query_Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=50)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center', to='reader.Article_Reader_Query')),
                ('cluster_articles', models.ManyToManyField(blank=True, related_name='cluster_articles', to='reader.Article_Reader_Query')),
            ],
        ),
        migrations.CreateModel(
            name='User_Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_output_articles', models.IntegerField(blank=True, null=True)),
                ('feeds', models.ManyToManyField(blank=True, to='scope.RSSFeed')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reader_query',
            name='user_reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.User_Reader'),
        ),
        migrations.AddField(
            model_name='article_reader_query',
            name='reader_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Reader_Query'),
        ),
    ]
