# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last24h', '0019_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
