# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last24h', '0025_alert_feeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='frequency',
            field=models.IntegerField(choices=[(10400, b'4 hours'), (31200, b'12 hours'), (62400, b'24 hours'), (172800, b'2 days'), (345600, b'4 days'), (604800, b'1 week')]),
        ),
    ]
