# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('last24h', '0026_auto_20160424_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send',
            name='email',
        ),
    ]
