# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last24h', '0028_suggest_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='custom',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='suggest',
            name='images',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='suggest',
            name='keywords',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='suggest',
            name='source',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='suggest',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='suggest',
            name='url',
            field=models.CharField(max_length=400),
        ),
    ]
