# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-11-27 14:52


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
            ],
        ),
    ]
