# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-04 20:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0008_auto_20161204_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
