# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-04 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0009_auto_20161204_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
