# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scope', '0011_auto_20161205_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentImap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100)),
                ('pwd', models.CharField(blank=True, max_length=100)),
                ('imap', models.CharField(blank=True, max_length=100)),
                ('mailbox', models.CharField(blank=True, max_length=100)),
                ('interval', models.IntegerField(blank=True, default=24)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='source',
            name='url',
        ),
        migrations.AddField(
            model_name='source',
            name='agent_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='agent_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.SlugField(),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
