# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-11 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0013_auto_20161205_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scope.Customer'),
        ),
    ]
