# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-11 11:12


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scope', '0014_userprofile_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_customer_id', models.PositiveIntegerField()),
                ('agent_id', models.PositiveIntegerField()),
                ('agent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_type', to='contenttypes.ContentType')),
                ('product_customer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_customer', to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='source',
            name='agent_id',
        ),
        migrations.RemoveField(
            model_name='source',
            name='agent_type',
        ),
        migrations.RemoveField(
            model_name='source',
            name='product_customer_id',
        ),
        migrations.RemoveField(
            model_name='source',
            name='product_customer_type',
        ),
        migrations.AddField(
            model_name='source',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
