# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-12 21:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0015_auto_20161211_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
