# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-13 22:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0017_auto_20161213_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
