# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-15 12:53


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0017_auto_20161213_1946'),
        ('scope', '0018_auto_20161213_2251'),
    ]

    operations = [
    ]
