# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-30 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0019_merge_20161215_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='key_expires',
            new_name='expires',
        ),
    ]
