# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-16 09:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0020_auto_20161230_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pubdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
