# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2017-01-29 10:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0021_article_pubdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentNewspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
