# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0023_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='keywords',
        ),
        migrations.AddField(
            model_name='article',
            name='sample',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
