# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0025_rssfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sample',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
