# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scope', '0026_auto_20170711_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
    ]
