# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-12-01 10:42


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
