# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-11-25 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Select_NH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_mistake', models.BooleanField(default=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=900)),
                ('url', models.CharField(max_length=900)),
                ('summary', models.CharField(max_length=1000)),
                ('keywords', models.CharField(max_length=900)),
                ('images', models.CharField(max_length=900)),
                ('source', models.CharField(max_length=900)),
            ],
        ),
    ]
