# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='select_nh',
            old_name='mistake',
            new_name='is_mistake',
        ),
    ]
