# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curate', '0028_curate_recipient_is_editor'),
        ('scope', '0024_auto_20170611_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curate_Click_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_opened', models.DateTimeField()),
                ('article_curate_query', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='curate.Article_Curate_Query')),
                ('recipient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='curate.Curate_Recipient')),
            ],
        ),
        migrations.CreateModel(
            name='Curate_Open_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_opened', models.DateTimeField()),
                ('curate_query', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='curate.Curate_Query')),
                ('recipient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='curate.Curate_Recipient')),
            ],
        ),
        migrations.CreateModel(
            name='Source_Click_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_opened', models.DateTimeField()),
                ('recipient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='curate.Curate_Recipient')),
                ('source', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scope.Source')),
            ],
        ),
    ]
