# -*- coding: utf-8 -*-

""" Local settings.

Django settings for graphite project.
bladibli
Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/

"""

from .importer import ImportGlobal
import djcelery
from .base import *

im = ImportGlobal()

DEBUG = False
ALLOWED_HOSTS = ['.grpht.info', '46.101.94.4', '.scope.ai']
CURRENT_DOMAIN = 'http://www.scope.ai'
CURRENT_NAME = 'scope'

ADMINS = ('GRPHT', 'grphtcontact@gmail.com', 'admin@scope.ai')
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'explore',
    'scope',
    'alert',
    'captcha',
    'curate',
    'twitter_bootstrap',
    'django.contrib.sites',
    'widget_tweaks',
    'djangobower',
    'djcelery',
    'kombu.transport.django')

djcelery.setup_loader()

BROKER_URL = im.get_env_variable('BROKER_URL')
CELERY_ACCEPT_CONTENT = ['pickle',
                         'json',
                         'msgpack',
                         'yaml']

LOCKDOWN_PASSWORDS = ('scope2016')
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
LOCKDOWN_URL_EXCEPTIONS = (
    r'^/$',
    r'pydata$',
    # r'lichtenfels$',
    r'contact$'
 )

DATABASES = {'default': {'ENGINE': 'django.db.backends.postgresql_psycopg2',
                         'NAME': im.get_env_variable('DATABASE_NAME'),
                         'USER': im.get_env_variable('DATABASE_USER'),
                         'PASSWORD': im.get_env_variable('DATABASE_PASSWORD'),
                         'HOST': im.get_env_variable('DATABASE_HOST'),
                         'PORT': im.get_env_variable('DATABASE_PORT')}}
